pipeline {
    agent any

    options {
        timestamps()
    }

    environment {
        GIT_CREDENTIALS = 'github-alx'
    }

    stages {
        stage('Checkout') {
            steps {
                echo "Checking out code from Git..."
                git branch: 'main',
                    credentialsId: "${GIT_CREDENTIALS}",
                    url: 'https://github.com/Lusanda-Hlela/alx-backend-python.git'
            }
        }

        stage('Set Up Virtual Environment') {
            steps {
                echo "Setting up Python virtual environment..."
                sh '''
                    python3 -m venv venv
                    source venv/bin/activate
                    pip install --upgrade pip
                '''
            }
        }

        stage('Install Dependencies') {
            steps {
                echo "Installing dependencies..."
                sh '''
                    source venv/bin/activate
                    pip install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Test') {
            steps {
                echo "Running tests..."
                sh '''
                    source venv/bin/activate
                    pytest messaging_app/
                '''
            }
        }

        stage('Deploy') {
            steps {
                echo "Deploying..."
                // Add your deploy steps here
            }
        }
    }
}

// ["pip3 install"]